slogo_team11: FrontEnd.HistoryBox Class Reference
FrontEnd.HistoryBox Class Reference
Public Member Functions
HistoryBox (UserCommands myCombo, String promptText)
void addEntry (String instruction)
String getMostRecentCommand ()
Private Attributes
UserCommands myComboBox
List< String > commandHistory
Detailed Description
Stores the history of commands
Author
Rica
Definition at line 12 of file HistoryBox.java.
Constructor & Destructor Documentation
FrontEnd.HistoryBox.HistoryBox (UserCommands myCombo, String promptText)
Constructs a history box of preferred size and wrap text with prompt text Also has combo box so that it can update with new instructions
Parameters
myCombo
promptText
Definition at line 22 of file HistoryBox.java.
References FrontEnd.View.HISTORY_BOX_HEIGHT, and FrontEnd.View.HISTORY_BOX_WIDTH.
Member Function Documentation
void FrontEnd.HistoryBox.addEntry (String instruction)
Definition at line 30 of file HistoryBox.java.
References FrontEnd.UserCommands.addCommand().
Referenced by FrontEnd.View.addHistoryEntry().
String FrontEnd.HistoryBox.getMostRecentCommand ()
Definition at line 36 of file HistoryBox.java.
Referenced by FrontEnd.CommandLine.handle().
Member Data Documentation
List<String> FrontEnd.HistoryBox.commandHistory private
Definition at line 14 of file HistoryBox.java.
UserCommands FrontEnd.HistoryBox.myComboBox private
Definition at line 13 of file HistoryBox.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEnd/HistoryBox.java