slogo_team11: FrontEnd.LanguageSelector Class Reference
FrontEnd.LanguageSelector Class Reference
Public Member Functions
LanguageSelector (BorderPane myRoot)
ComboBox< String > getComboBox ()
String getCurrentLanguage ()
Private Member Functions
void handle ()
String translate (String currentText)
ObservableList< Node > rootChildren (Node n)
Private Attributes
ResourceBundle myLanguages = ResourceBundle.getBundle(DefaultStrings.DEFAULT_RESOURCE_PACKAGE)
ObservableList< Node > myRootChildren
ComboBox< String > myComboBox
List< Node > leaves = new ArrayList<Node>()
int languageNum
Detailed Description
Stores a list of commands that the user created. These commands can be clicked to be re-run.
Author
Rica
Definition at line 21 of file LanguageSelector.java.
Constructor & Destructor Documentation
FrontEnd.LanguageSelector.LanguageSelector (BorderPane myRoot)
Constructs language selector which includes combo box and has access to the borderpane root
Parameters
buttonWidth
myRoot
Definition at line 36 of file LanguageSelector.java.
References FrontEnd.DefaultStrings.ENGLISH, FrontEnd.LanguageSelector.handle(), FrontEnd.View.LANGUAGESELECTOR_CB_WIDTH, and FrontEnd.StringChooser.myLanguageOrder.
Member Function Documentation
ComboBox<String> FrontEnd.LanguageSelector.getComboBox ()
Returns
Returns language selector combo box
Definition at line 158 of file LanguageSelector.java.
References FrontEnd.LanguageSelector.myComboBox.
Referenced by FrontEnd.View.getCurrentLanguage(), FrontEndCommands.LoadWorkspace.getSettingsFromFile(), and FrontEnd.View.View().
String FrontEnd.LanguageSelector.getCurrentLanguage ()
Definition at line 162 of file LanguageSelector.java.
Referenced by FrontEndCommands.SaveWorkspace.writeSettingsToFile().
void FrontEnd.LanguageSelector.handle () private
Gets all the leaf nodes of the children and stores it in the list leaves. Translates the leaf into the selected language by calling the translate method.
Definition at line 94 of file LanguageSelector.java.
References FrontEnd.StringChooser.myLanguageOrder, FrontEnd.LanguageSelector.rootChildren(), and FrontEnd.LanguageSelector.translate().
Referenced by FrontEnd.LanguageSelector.LanguageSelector().
ObservableList<Node> FrontEnd.LanguageSelector.rootChildren (Node n) private
Recursive method to construct the list of all leaf nodes
Parameters
n
Returns
ObservableList<Node> of all leaves
Definition at line 141 of file LanguageSelector.java.
Referenced by FrontEnd.LanguageSelector.handle().
String FrontEnd.LanguageSelector.translate (String currentText) private
Translates the text in the leaf node to the appropriate language and passes it back to the handle method.
Parameters
currentText
Returns
Definition at line 126 of file LanguageSelector.java.
Referenced by FrontEnd.LanguageSelector.handle().
Member Data Documentation
int FrontEnd.LanguageSelector.languageNum private
Definition at line 29 of file LanguageSelector.java.
List<Node> FrontEnd.LanguageSelector.leaves = new ArrayList<Node>() private
Definition at line 28 of file LanguageSelector.java.
ComboBox<String> FrontEnd.LanguageSelector.myComboBox private
Definition at line 27 of file LanguageSelector.java.
Referenced by FrontEnd.LanguageSelector.getComboBox().
ResourceBundle FrontEnd.LanguageSelector.myLanguages = ResourceBundle.getBundle(DefaultStrings.DEFAULT_RESOURCE_PACKAGE) private
Definition at line 23 of file LanguageSelector.java.
ObservableList<Node> FrontEnd.LanguageSelector.myRootChildren private
Definition at line 26 of file LanguageSelector.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEnd/LanguageSelector.java