slogo_team11: Pen.PenTypeBox Class Reference
Pen.PenTypeBox Class Reference
Public Member Functions
PenTypeBox ()
List< Double > getType ()
Private Member Functions
void initMap ()
Private Attributes
Map< String, List< Double > > myMap
Detailed Description
Definition at line 9 of file PenTypeBox.java.
Constructor & Destructor Documentation
Pen.PenTypeBox.PenTypeBox ()
Definition at line 13 of file PenTypeBox.java.
References Pen.PenTypeBox.initMap(), and FrontEnd.DefaultStrings.SOLID_LABEL.
Member Function Documentation
List<Double> Pen.PenTypeBox.getType ()
Definition at line 21 of file PenTypeBox.java.
Referenced by Pen.PenOptions.setUpBoxes().
void Pen.PenTypeBox.initMap () private
Definition at line 25 of file PenTypeBox.java.
References FrontEnd.DefaultStrings.DASHED_LABEL, FrontEnd.DefaultStrings.DOTTED_LABEL, and FrontEnd.DefaultStrings.SOLID_LABEL.
Referenced by Pen.PenTypeBox.PenTypeBox().
Member Data Documentation
Map<String, List<Double> > Pen.PenTypeBox.myMap private
Definition at line 11 of file PenTypeBox.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Pen/PenTypeBox.java