slogo_team11: FrontEndCommands.LoadWorkspace Class Reference
FrontEndCommands.LoadWorkspace Class Reference
Public Member Functions
LoadWorkspace (View myView)
Button getButton ()
Private Member Functions
void handle ()
void getSettingsFromFile ()
Private Attributes
Button myButton
String myLanguage
View myView
String myBackgroundColor
TurtleImageBox myTurtleImageBox
File selectedFile
int myNumberTurtles
Detailed Description
Allows users to set, save, and load workspace preferences (like default background, starting image list, starting number of turtles, starting file to load, command language, etc.)
Author
Rica
Definition at line 19 of file LoadWorkspace.java.
Constructor & Destructor Documentation
FrontEndCommands.LoadWorkspace.LoadWorkspace (View myView)
Definition at line 28 of file LoadWorkspace.java.
References FrontEndCommands.LoadWorkspace.handle(), FrontEnd.DefaultStrings.LOAD_WORKSPACE, FrontEndCommands.LoadWorkspace.myView, and FrontEnd.View.SIDEBAR_BUTTON_WIDTH.
Member Function Documentation
Button FrontEndCommands.LoadWorkspace.getButton ()
Definition at line 83 of file LoadWorkspace.java.
References FrontEndCommands.LoadWorkspace.myButton.
Referenced by FrontEnd.View.View().
void FrontEndCommands.LoadWorkspace.getSettingsFromFile () private
Definition at line 47 of file LoadWorkspace.java.
References FrontEnd.View.getAddTurtleButton(), FrontEnd.LanguageSelector.getComboBox(), FrontEnd.View.getLanguageSelector(), FrontEnd.View.getMyBackgroundColorBox(), FrontEnd.View.getMyTurtleImageBox(), FrontEndCommands.LoadWorkspace.handle(), FrontEnd.View.makeErrorDialog(), and FrontEndCommands.LoadWorkspace.myNumberTurtles.
Referenced by FrontEndCommands.LoadWorkspace.handle().
void FrontEndCommands.LoadWorkspace.handle () private
Definition at line 35 of file LoadWorkspace.java.
References FrontEndCommands.LoadWorkspace.getSettingsFromFile().
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile(), and FrontEndCommands.LoadWorkspace.LoadWorkspace().
Member Data Documentation
String FrontEndCommands.LoadWorkspace.myBackgroundColor private
Definition at line 23 of file LoadWorkspace.java.
Button FrontEndCommands.LoadWorkspace.myButton private
Definition at line 20 of file LoadWorkspace.java.
Referenced by FrontEndCommands.LoadWorkspace.getButton().
String FrontEndCommands.LoadWorkspace.myLanguage private
Definition at line 21 of file LoadWorkspace.java.
int FrontEndCommands.LoadWorkspace.myNumberTurtles private
Definition at line 26 of file LoadWorkspace.java.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile().
TurtleImageBox FrontEndCommands.LoadWorkspace.myTurtleImageBox private
Definition at line 24 of file LoadWorkspace.java.
View FrontEndCommands.LoadWorkspace.myView private
Definition at line 22 of file LoadWorkspace.java.
Referenced by FrontEndCommands.LoadWorkspace.LoadWorkspace().
File FrontEndCommands.LoadWorkspace.selectedFile private
Definition at line 25 of file LoadWorkspace.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEndCommands/LoadWorkspace.java