slogo_team11: TurtleView.PointConverter Class Reference
TurtleView.PointConverter Class Reference
Static Public Member Functions
static double convertUserToActualX (double x)
static double convertUserToActualY (double y)
static Point2D convertUserToActualPoint (Point2D p)
static double convertActualToUserX (double x)
static double convertActualToUserY (double y)
static Point2D convertActualToUserPoint (Point2D p)
Detailed Description
Converts the point to the xy coordinate system that the user sees
Author
Rica
Definition at line 11 of file PointConverter.java.
Member Function Documentation
static Point2D TurtleView.PointConverter.convertActualToUserPoint (Point2D p) static
Definition at line 33 of file PointConverter.java.
References TurtleView.PointConverter.convertUserToActualX(), and TurtleView.PointConverter.convertUserToActualY().
static double TurtleView.PointConverter.convertActualToUserX (double x) static
Definition at line 25 of file PointConverter.java.
References FrontEnd.View.TURTLEWINDOW_WIDTH.
Referenced by Nodes.turtlecommands.XCoordinateNode.update().
static double TurtleView.PointConverter.convertActualToUserY (double y) static
Definition at line 29 of file PointConverter.java.
References FrontEnd.View.TURTLEWINDOW_HEIGHT.
Referenced by Nodes.turtlecommands.YCoordinateNode.update().
static Point2D TurtleView.PointConverter.convertUserToActualPoint (Point2D p) static
Definition at line 20 of file PointConverter.java.
References TurtleView.PointConverter.convertUserToActualX(), and TurtleView.PointConverter.convertUserToActualY().
Referenced by Nodes.turtlecommands.HomeNode.update(), Nodes.turtlecommands.SetTowardsNode.update(), and Nodes.turtlecommands.SetPositionNode.update().
static double TurtleView.PointConverter.convertUserToActualX (double x) static
Definition at line 12 of file PointConverter.java.
References FrontEnd.View.TURTLEWINDOW_WIDTH.
Referenced by TurtleView.PointConverter.convertActualToUserPoint(), and TurtleView.PointConverter.convertUserToActualPoint().
static double TurtleView.PointConverter.convertUserToActualY (double y) static
Definition at line 16 of file PointConverter.java.
References FrontEnd.View.TURTLEWINDOW_HEIGHT.
Referenced by TurtleView.PointConverter.convertActualToUserPoint(), and TurtleView.PointConverter.convertUserToActualPoint().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/TurtleView/PointConverter.java