slogo_team11: Backend.Model Class Reference
Backend.Model Class Reference
Public Member Functions
Model ()
Model (String input)
Parser getParser ()
SceneUpdater parse (String instruction, List< Turtle > activeTurtles, String language)
Protected Attributes
String myInput
Package Attributes
List< Double > printValues
Private Member Functions
boolean makeTreeandAddValues (String instruction, Turtle t, String language)
Private Attributes
Parser myParser
AST tree
Map< String, ConstantNode > userSaves
Detailed Description
The Model serves as the overarching class for the back end. It builds the Abstract Syntax Tree (AST) by using a Parser to parse the instruction passed from the controller. The back end can detect syntax errors and uses reflection to create the tree.
Author
Ashwin, Justin, Greg
Definition at line 19 of file Model.java.
Constructor & Destructor Documentation
Backend.Model.Model ()
Definition at line 27 of file Model.java.
Backend.Model.Model (String input)
Definition at line 33 of file Model.java.
Member Function Documentation
Parser Backend.Model.getParser ()
Definition at line 37 of file Model.java.
References Backend.Model.myParser.
boolean Backend.Model.makeTreeandAddValues (String instruction, Turtle t, String language) private
Definition at line 55 of file Model.java.
References Backend.Parser.getMap(), Backend.Parser.getNoError(), Backend.Parser.getQueueOfNodes(), Backend.Parser.newInfo(), and Backend.AST.populateTree().
Referenced by Backend.Model.parse().
SceneUpdater Backend.Model.parse (String instruction, List< Turtle > activeTurtles, String language)
Definition at line 41 of file Model.java.
References Backend.Model.makeTreeandAddValues().
Referenced by FrontEnd.Controller.executeCommand().
Member Data Documentation
String Backend.Model.myInput protected
Definition at line 21 of file Model.java.
Parser Backend.Model.myParser private
Definition at line 22 of file Model.java.
Referenced by Backend.Model.getParser().
List<Double> Backend.Model.printValues package
Definition at line 24 of file Model.java.
AST Backend.Model.tree private
Definition at line 23 of file Model.java.
Map<String, ConstantNode> Backend.Model.userSaves private
Definition at line 25 of file Model.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Backend/Model.java