slogo_team11: Pen.PenColorBox Class Reference
Pen.PenColorBox Class Reference
Public Member Functions
PenColorBox ()
Color getColor ()
Private Member Functions
void initMap ()
Private Attributes
Map< String, Color > myMap
Detailed Description
Changes color of turtle pen
Author
Greg, Rica
Definition at line 15 of file PenColorBox.java.
Constructor & Destructor Documentation
Pen.PenColorBox.PenColorBox ()
Definition at line 18 of file PenColorBox.java.
References FrontEnd.DefaultStrings.BLACK, Pen.PenColorBox.initMap(), and FrontEnd.View.SIDEBAR_COMBOBOX_WIDTH.
Member Function Documentation
Color Pen.PenColorBox.getColor ()
Definition at line 34 of file PenColorBox.java.
Referenced by Pen.PenOptions.setUpBoxes().
void Pen.PenColorBox.initMap () private
Definition at line 26 of file PenColorBox.java.
References FrontEnd.DefaultStrings.BLACK, FrontEnd.DefaultStrings.BLUE, FrontEnd.DefaultStrings.GREEN, and FrontEnd.DefaultStrings.RED.
Referenced by Pen.PenColorBox.PenColorBox().
Member Data Documentation
Map<String, Color> Pen.PenColorBox.myMap private
Definition at line 16 of file PenColorBox.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Pen/PenColorBox.java