slogo_team11: Backend.Turtle Class Reference
Backend.Turtle Class Reference
Public Member Functions
Turtle (Point2D location, double angle, int id)
Turtle ()
void setPenDown ()
void setPenUp ()
boolean penStatus ()
Point2D getLocation ()
void setAngle (double angle)
double getAngle ()
void addLocation (Point2D location)
Point2D nextLocation (double distance, double angle)
List< Point2D > getNextLocations ()
void move (Point2D point)
Pen getPen ()
PenOptions getPenOptions ()
TurtleImageBox getImageBox ()
void changeToDefaultImage (String imageName)
void changeToLoadedImage (String imageLocation)
void hide ()
void show ()
Polyline moveAndDrawPath ()
double getXCord ()
double getYCord ()
void showRing ()
void hideRing ()
ActiveRing getRing ()
int getID ()
void setClear ()
void clearTrail ()
List< Polyline > getTrail ()
boolean needsClear ()
Static Public Attributes
static final double DEFAULT_WIDTH = 25.0
static final double DEFAULT_HEIGHT = 25.0
static final String DEFAULT_IMAGE = "turtle1"
static final String IMAGE_ERROR = "This turtle image does not exist: "
Private Attributes
Point2D myLocation
List< Point2D > nextLocations
double myAngle
Pen myPen
PenOptions myPenOptions
TurtleImageBox myImageBox
TurtleInformation myTurtleInformation
ActiveRing myRing
int myID
boolean needsClear
List< Polyline > myTrail
Detailed Description
Author
Ashwin, Justin, Greg, Rica
This Turtle class is used by both the front end and the back end. It extends ImageView so that it can be added directly to the Scene as a visual representation, but it also holds much data and has many methods for updating its state.
Definition at line 33 of file Turtle.java.
Constructor & Destructor Documentation
Backend.Turtle.Turtle (Point2D location, double angle, int id)
Definition at line 54 of file Turtle.java.
References Backend.Turtle.changeToDefaultImage(), Backend.Turtle.DEFAULT_HEIGHT, Backend.Turtle.DEFAULT_WIDTH, Backend.Turtle.hideRing(), and Backend.Turtle.move().
Backend.Turtle.Turtle ()
Definition at line 76 of file Turtle.java.
Member Function Documentation
void Backend.Turtle.addLocation (Point2D location)
Definition at line 103 of file Turtle.java.
References FrontEnd.Boundary.checkBoundary(), Backend.Turtle.move(), FrontEnd.View.TURTLEWINDOW_HEIGHT, and FrontEnd.View.TURTLEWINDOW_WIDTH.
Referenced by Nodes.turtlecommands.BackwardNode.update(), Nodes.turtlecommands.HomeNode.update(), Nodes.turtlecommands.SetPositionNode.update(), and Nodes.turtlecommands.ForwardNode.update().
void Backend.Turtle.changeToDefaultImage (String imageName)
Definition at line 144 of file Turtle.java.
Referenced by TurtleView.TurtleImageBox.handle(), and Backend.Turtle.Turtle().
void Backend.Turtle.changeToLoadedImage (String imageLocation)
Definition at line 156 of file Turtle.java.
Referenced by TurtleView.TurtleImageBox.handle().
void Backend.Turtle.clearTrail ()
Definition at line 219 of file Turtle.java.
double Backend.Turtle.getAngle ()
Definition at line 99 of file Turtle.java.
References Backend.Turtle.myAngle.
Referenced by Nodes.turtlecommands.LeftNode.update(), and Nodes.turtlecommands.RightNode.update().
int Backend.Turtle.getID ()
Definition at line 211 of file Turtle.java.
References Backend.Turtle.myID.
Referenced by Nodes.turtlecommands.IDNode.update(), and TurtleView.TurtleInformation.update().
TurtleImageBox Backend.Turtle.getImageBox ()
Definition at line 140 of file Turtle.java.
References Backend.Turtle.myImageBox.
Point2D Backend.Turtle.getLocation ()
Definition at line 91 of file Turtle.java.
References Backend.Turtle.myLocation.
Referenced by Backend.Turtle.getXCord(), Backend.Turtle.getYCord(), Nodes.turtlecommands.HomeNode.update(), and Nodes.turtlecommands.SetPositionNode.update().
List<Point2D> Backend.Turtle.getNextLocations ()
Definition at line 120 of file Turtle.java.
References Backend.Turtle.nextLocations.
Pen Backend.Turtle.getPen ()
Definition at line 132 of file Turtle.java.
References Backend.Turtle.myPen.
Referenced by TurtleView.TurtleWindow.click().
PenOptions Backend.Turtle.getPenOptions ()
Definition at line 136 of file Turtle.java.
References Backend.Turtle.myPenOptions.
ActiveRing Backend.Turtle.getRing ()
Definition at line 207 of file Turtle.java.
References Backend.Turtle.myRing.
List<Polyline> Backend.Turtle.getTrail ()
Definition at line 224 of file Turtle.java.
References Backend.Turtle.myTrail.
double Backend.Turtle.getXCord ()
Definition at line 191 of file Turtle.java.
References Backend.Turtle.getLocation().
Referenced by Nodes.turtlecommands.XCoordinateNode.update(), Nodes.turtlecommands.SetTowardsNode.update(), and TurtleView.TurtleInformation.update().
double Backend.Turtle.getYCord ()
Definition at line 195 of file Turtle.java.
References Backend.Turtle.getLocation().
Referenced by Nodes.turtlecommands.YCoordinateNode.update(), Nodes.turtlecommands.SetTowardsNode.update(), and TurtleView.TurtleInformation.update().
void Backend.Turtle.hide ()
Definition at line 176 of file Turtle.java.
Referenced by Nodes.turtlecommands.HideTurtleNode.update().
void Backend.Turtle.hideRing ()
Definition at line 203 of file Turtle.java.
Referenced by TurtleView.TurtleWindow.click(), and Backend.Turtle.Turtle().
void Backend.Turtle.move (Point2D point)
Definition at line 124 of file Turtle.java.
References TurtleView.ActiveRing.update(), and TurtleView.TurtleInformation.update().
Referenced by Backend.Turtle.addLocation(), and Backend.Turtle.Turtle().
Polyline Backend.Turtle.moveAndDrawPath ()
Definition at line 184 of file Turtle.java.
References Pen.Pen.drawLines().
boolean Backend.Turtle.needsClear ()
Definition at line 228 of file Turtle.java.
Point2D Backend.Turtle.nextLocation (double distance, double angle)
Definition at line 111 of file Turtle.java.
Referenced by Nodes.turtlecommands.BackwardNode.update(), and Nodes.turtlecommands.ForwardNode.update().
boolean Backend.Turtle.penStatus ()
Definition at line 87 of file Turtle.java.
References Pen.Pen.isDown().
Referenced by Nodes.turtlecommands.IsPenDownNode.update().
void Backend.Turtle.setAngle (double angle)
Definition at line 95 of file Turtle.java.
Referenced by Nodes.turtlecommands.LeftNode.update(), Nodes.turtlecommands.RightNode.update(), Nodes.turtlecommands.SetHeadingNode.update(), and Nodes.turtlecommands.SetTowardsNode.update().
void Backend.Turtle.setClear ()
Definition at line 215 of file Turtle.java.
Referenced by Nodes.turtlecommands.ClearScreenNode.update().
void Backend.Turtle.setPenDown ()
Definition at line 79 of file Turtle.java.
References Pen.Pen.setPenDown().
Referenced by Nodes.turtlecommands.PenDownNode.update().
void Backend.Turtle.setPenUp ()
Definition at line 83 of file Turtle.java.
References Pen.Pen.setPenUp().
Referenced by Nodes.turtlecommands.PenUpNode.update().
void Backend.Turtle.show ()
Definition at line 180 of file Turtle.java.
Referenced by Nodes.turtlecommands.ShowTurtleNode.update().
void Backend.Turtle.showRing ()
Definition at line 199 of file Turtle.java.
Referenced by TurtleView.TurtleWindow.click().
Member Data Documentation
final double Backend.Turtle.DEFAULT_HEIGHT = 25.0 static
Definition at line 36 of file Turtle.java.
Referenced by Backend.Turtle.Turtle().
final String Backend.Turtle.DEFAULT_IMAGE = "turtle1" static
Definition at line 37 of file Turtle.java.
final double Backend.Turtle.DEFAULT_WIDTH = 25.0 static
Definition at line 35 of file Turtle.java.
Referenced by Backend.Turtle.Turtle().
final String Backend.Turtle.IMAGE_ERROR = "This turtle image does not exist: " static
Definition at line 38 of file Turtle.java.
double Backend.Turtle.myAngle private
Definition at line 43 of file Turtle.java.
Referenced by Backend.Turtle.getAngle().
int Backend.Turtle.myID private
Definition at line 49 of file Turtle.java.
Referenced by Backend.Turtle.getID().
TurtleImageBox Backend.Turtle.myImageBox private
Definition at line 46 of file Turtle.java.
Referenced by Backend.Turtle.getImageBox().
Point2D Backend.Turtle.myLocation private
Definition at line 41 of file Turtle.java.
Referenced by Backend.Turtle.getLocation().
Pen Backend.Turtle.myPen private
Definition at line 44 of file Turtle.java.
Referenced by Backend.Turtle.getPen().
PenOptions Backend.Turtle.myPenOptions private
Definition at line 45 of file Turtle.java.
Referenced by Backend.Turtle.getPenOptions().
ActiveRing Backend.Turtle.myRing private
Definition at line 48 of file Turtle.java.
Referenced by Backend.Turtle.getRing().
List<Polyline> Backend.Turtle.myTrail private
Definition at line 51 of file Turtle.java.
Referenced by Backend.Turtle.getTrail().
TurtleInformation Backend.Turtle.myTurtleInformation private
Definition at line 47 of file Turtle.java.
boolean Backend.Turtle.needsClear private
Definition at line 50 of file Turtle.java.
List<Point2D> Backend.Turtle.nextLocations private
Definition at line 42 of file Turtle.java.
Referenced by Backend.Turtle.getNextLocations().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Backend/Turtle.java