slogo_team11: FrontEnd.View Class Reference
FrontEnd.View Class Reference
Public Member Functions
View ()
Stage makeErrorDialog (String message, String command)
Scene getScene ()
String getCurrentLanguage ()
TurtleWindow getTurtleWindow ()
TurtleInformation getTurtleInfo ()
void addController (Controller c)
LanguageSelector getLanguageSelector ()
BackgroundColorBox getMyBackgroundColorBox ()
TurtleImageBox getMyTurtleImageBox ()
Button getAddTurtleButton ()
GridCheckBox getMyGridCheckBox ()
void addHistoryEntry (String instruction)
void addConsoleEntries (List< Double > returnValues)
void updateFocus ()
void updateTurtleInfo (List< Turtle > activeTurtles)
void updateUserVariables (List< String > variables)
Static Public Attributes
static final int SHORT_BUTTON_HEIGHT = 30
static final int PUFFY_BUTTON_HEIGHT = 60
static final int LANGUAGESELECTOR_CB_WIDTH = 100
static final int NEWWORKSPACE_BUTTON_WIDTH = 100
static final int GO_BUTTON_WIDTH = 50
static final int ENTERCLEAR_BUTTON_WIDTH = 100
static final int COMMANDLINE_WIDTH = 500
static final int COMMANDLINE_HEIGHT = 150
static final int HISTORY_BOX_WIDTH = 400
static final int HISTORY_BOX_HEIGHT = 400
static final int SIDEBAR_WIDTH = 250
static final int SIDEBAR_BUTTON_WIDTH = 200
static final int SIDEBAR_AMOUNT_BUTTON_WIDTH = 125
static final int SIDEBAR_AMOUNT_WIDTH = 75
static final int SIDEBAR_COMBOBOX_WIDTH = 200
static final Dimension DEFAULT_SIZE = new Dimension(1200, 600)
static final double DIALOG_WIDTH = 400
static final double DIALOG_HEIGHT = 100
static final Insets PADDING = new Insets(5)
static final int BOX_SPACING = 5
static final double TURTLEWINDOW_WIDTH = 600.0
static final double TURTLEWINDOW_HEIGHT = 400.0
static final boolean DEFAULT_GRIDLINES = true
static final String DEFAULT_LANGUAGE = DefaultStrings.ENGLISH
static final double ERROR_HEIGHT = 30
static final double ERROR_WIDTH = 30
Package Attributes
BorderPane root
Private Member Functions
void sendArrowCommand (KeyEvent ke)
Button makeClearButton ()
void makeTurtleButton ()
void makeTextAreas ()
void makeEnterButton ()
Private Attributes
Scene myScene
Controller myController
HBox topHBox = new HBox(BOX_SPACING)
VBox leftVBox = new VBox(BOX_SPACING)
VBox centerVBox = new VBox(BOX_SPACING)
VBox sidebarVBox = new VBox(BOX_SPACING)
HBox usercmdHBox = new HBox(BOX_SPACING)
HBox uservrbHBox = new HBox(BOX_SPACING)
HBox bottomLeftHBox = new HBox(BOX_SPACING)
VBox enterclearVBox = new VBox(BOX_SPACING)
VBox backgroundBox = new VBox()
VBox imageBox = new VBox()
HBox gridBox = new HBox(BOX_SPACING)
CommandLine myCommandLine
Button addTurtleButton
HistoryBox myHistoryBox
Console myConsole
TurtleWindow myTurtleWindow
ArrowKeyHandler myArrowHandler
CommandFactory myCommandFactory
SuperCommand myEnterCommand
List< SuperCommand > myButtons
UserCommands dropdownCommandMenu
UserVariablesStorage dropdownVariablesMenu
LanguageSelector myLanguageSelector
TurtleInformation myTurtleInformation
PenOptions myPenBox
BackgroundColorBox myBackgroundColorBox
TurtleImageBox myTurtleImageBox
GridCheckBox myGridCheckBox
Detailed Description
The View is the overall container class for the front end. It holds all of the GUI components and has various methods to update its state.
Author
Rica Zhang, Greg Lyons
Definition at line 43 of file View.java.
Constructor & Destructor Documentation
FrontEnd.View.View ()
Constructs the view
Parameters
language
Definition at line 111 of file View.java.
References FrontEnd.DefaultStrings.BACKGROUNDCOLOR, FrontEnd.DefaultStrings.DISPLAYGRIDLINES, FrontEndCommands.NewWorkspace.getButton(), FrontEndCommands.SuperCommand.getButton(), FrontEndCommands.SaveWorkspace.getButton(), FrontEndCommands.LoadWorkspace.getButton(), FrontEnd.UserVariablesStorage.getComboBox(), FrontEnd.UserCommands.getComboBox(), FrontEnd.LanguageSelector.getComboBox(), FrontEnd.CommandFactory.getCommandButtons(), FrontEndCommands.SuperCommand.getHBox(), FrontEnd.StringChooser.getWordInLang(), FrontEnd.View.makeClearButton(), FrontEnd.CommandFactory.makeCommand(), FrontEnd.View.makeEnterButton(), FrontEnd.View.makeTextAreas(), FrontEnd.View.makeTurtleButton(), FrontEnd.View.sendArrowCommand(), FrontEnd.DefaultStrings.TURTLEIMAGE, and FrontEnd.View.updateFocus().
Member Function Documentation
void FrontEnd.View.addConsoleEntries (List< Double > returnValues)
Definition at line 314 of file View.java.
Referenced by FrontEnd.Controller.interpret().
void FrontEnd.View.addController (Controller c)
Definition at line 279 of file View.java.
Referenced by FrontEnd.Workspace.Workspace().
void FrontEnd.View.addHistoryEntry (String instruction)
Definition at line 310 of file View.java.
References FrontEnd.HistoryBox.addEntry().
Referenced by FrontEnd.Controller.interpret().
Button FrontEnd.View.getAddTurtleButton ()
Definition at line 302 of file View.java.
References FrontEnd.View.addTurtleButton.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile().
String FrontEnd.View.getCurrentLanguage ()
Definition at line 267 of file View.java.
References FrontEnd.LanguageSelector.getComboBox().
Referenced by FrontEnd.Controller.executeCommand().
LanguageSelector FrontEnd.View.getLanguageSelector ()
Definition at line 289 of file View.java.
References FrontEnd.View.myLanguageSelector.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile(), and FrontEndCommands.SaveWorkspace.writeSettingsToFile().
BackgroundColorBox FrontEnd.View.getMyBackgroundColorBox ()
Definition at line 294 of file View.java.
References FrontEnd.View.myBackgroundColorBox.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile(), and FrontEndCommands.SaveWorkspace.writeSettingsToFile().
GridCheckBox FrontEnd.View.getMyGridCheckBox ()
Definition at line 306 of file View.java.
References FrontEnd.View.myGridCheckBox.
TurtleImageBox FrontEnd.View.getMyTurtleImageBox ()
Definition at line 298 of file View.java.
References FrontEnd.View.myTurtleImageBox.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile().
Scene FrontEnd.View.getScene ()
Definition at line 263 of file View.java.
References FrontEnd.View.myScene.
Referenced by FrontEnd.Workspace.Workspace().
TurtleInformation FrontEnd.View.getTurtleInfo ()
Definition at line 275 of file View.java.
References FrontEnd.View.myTurtleInformation.
Referenced by FrontEnd.Controller.Controller().
TurtleWindow FrontEnd.View.getTurtleWindow ()
Definition at line 271 of file View.java.
References FrontEnd.View.myTurtleWindow.
Referenced by FrontEnd.Controller.Controller(), and FrontEndCommands.SaveWorkspace.writeSettingsToFile().
Button FrontEnd.View.makeClearButton () private
Creates a clear button that clears the command line when pressed. This is not included in the command factory because it is not a subclass of SuperCommand since it is very simple and doesn't need the features that SuperCommand has.
Returns
clear button
Definition at line 214 of file View.java.
References FrontEnd.DefaultStrings.CLEAR, and FrontEnd.StringChooser.getWordInLang().
Referenced by FrontEnd.View.View().
void FrontEnd.View.makeEnterButton () private
Creates the Enter Button. This is not created in the button for loop above because it is in a different location than the other regular command buttons.
Definition at line 250 of file View.java.
References FrontEnd.DefaultStrings.ENTER, and FrontEnd.CommandFactory.makeCommand().
Referenced by FrontEnd.View.View().
Stage FrontEnd.View.makeErrorDialog (String message, String command)
Definition at line 254 of file View.java.
Referenced by FrontEndCommands.LoadWorkspace.getSettingsFromFile(), and FrontEnd.Controller.interpret().
void FrontEnd.View.makeTextAreas () private
Initializes the command line and the history box.
Definition at line 236 of file View.java.
References FrontEnd.DefaultStrings.COMMANDLINEDEFAULT, FrontEnd.DefaultStrings.CONSOLEDEFAULT, FrontEnd.StringChooser.getWordInLang(), FrontEnd.DefaultStrings.HISTORYBOXDEFAULT, and FrontEnd.View.myHistoryBox.
Referenced by FrontEnd.View.View().
void FrontEnd.View.makeTurtleButton () private
Definition at line 226 of file View.java.
References FrontEnd.StringChooser.getWordInLang(), TurtleView.TurtleWindow.makeTurtle(), and FrontEnd.DefaultStrings.TURTLEBUTTON.
Referenced by FrontEnd.View.View().
void FrontEnd.View.sendArrowCommand (KeyEvent ke) private
Definition at line 200 of file View.java.
References FrontEndCommands.SuperCommand.change(), FrontEnd.DefaultStrings.EMPTY, and FrontEnd.ArrowKeyHandler.makeInstruction().
Referenced by FrontEnd.View.View().
void FrontEnd.View.updateFocus ()
Definition at line 325 of file View.java.
Referenced by FrontEnd.Controller.executeCommand(), and FrontEnd.View.View().
void FrontEnd.View.updateTurtleInfo (List< Turtle > activeTurtles)
Definition at line 329 of file View.java.
References TurtleView.TurtleInformation.update().
Referenced by FrontEnd.Controller.interpret().
void FrontEnd.View.updateUserVariables (List< String > variables)
Definition at line 333 of file View.java.
References FrontEnd.UserVariablesStorage.update().
Member Data Documentation
Button FrontEnd.View.addTurtleButton private
Definition at line 87 of file View.java.
Referenced by FrontEnd.View.getAddTurtleButton().
VBox FrontEnd.View.backgroundBox = new VBox() private
Definition at line 82 of file View.java.
HBox FrontEnd.View.bottomLeftHBox = new HBox(BOX_SPACING) private
Definition at line 80 of file View.java.
final int FrontEnd.View.BOX_SPACING = 5 static
Definition at line 66 of file View.java.
Referenced by Pen.PenOptions.PenOptions(), and Pen.PenOptions.setUpBoxes().
VBox FrontEnd.View.centerVBox = new VBox(BOX_SPACING) private
Definition at line 76 of file View.java.
final int FrontEnd.View.COMMANDLINE_HEIGHT = 150 static
Definition at line 54 of file View.java.
Referenced by FrontEnd.CommandLine.CommandLine().
final int FrontEnd.View.COMMANDLINE_WIDTH = 500 static
Definition at line 53 of file View.java.
Referenced by FrontEnd.CommandLine.CommandLine().
final boolean FrontEnd.View.DEFAULT_GRIDLINES = true static
Definition at line 69 of file View.java.
final String FrontEnd.View.DEFAULT_LANGUAGE = DefaultStrings.ENGLISH static
Definition at line 70 of file View.java.
Referenced by FrontEndCommands.NewWorkspace.NewWorkspace().
final Dimension FrontEnd.View.DEFAULT_SIZE = new Dimension(1200, 600) static
Definition at line 62 of file View.java.
final double FrontEnd.View.DIALOG_HEIGHT = 100 static
Definition at line 64 of file View.java.
final double FrontEnd.View.DIALOG_WIDTH = 400 static
Definition at line 63 of file View.java.
UserCommands FrontEnd.View.dropdownCommandMenu private
Definition at line 97 of file View.java.
UserVariablesStorage FrontEnd.View.dropdownVariablesMenu private
Definition at line 98 of file View.java.
final int FrontEnd.View.ENTERCLEAR_BUTTON_WIDTH = 100 static
Definition at line 52 of file View.java.
Referenced by FrontEndCommands.EnterCommand.EnterCommand().
VBox FrontEnd.View.enterclearVBox = new VBox(BOX_SPACING) private
Definition at line 81 of file View.java.
final double FrontEnd.View.ERROR_HEIGHT = 30 static
Definition at line 71 of file View.java.
final double FrontEnd.View.ERROR_WIDTH = 30 static
Definition at line 72 of file View.java.
final int FrontEnd.View.GO_BUTTON_WIDTH = 50 static
Definition at line 51 of file View.java.
HBox FrontEnd.View.gridBox = new HBox(BOX_SPACING) private
Definition at line 84 of file View.java.
final int FrontEnd.View.HISTORY_BOX_HEIGHT = 400 static
Definition at line 56 of file View.java.
Referenced by FrontEnd.HistoryBox.HistoryBox().
final int FrontEnd.View.HISTORY_BOX_WIDTH = 400 static
Definition at line 55 of file View.java.
Referenced by FrontEnd.HistoryBox.HistoryBox().
VBox FrontEnd.View.imageBox = new VBox() private
Definition at line 83 of file View.java.
final int FrontEnd.View.LANGUAGESELECTOR_CB_WIDTH = 100 static
Definition at line 49 of file View.java.
Referenced by FrontEnd.LanguageSelector.LanguageSelector().
VBox FrontEnd.View.leftVBox = new VBox(BOX_SPACING) private
Definition at line 75 of file View.java.
ArrowKeyHandler FrontEnd.View.myArrowHandler private
Definition at line 91 of file View.java.
BackgroundColorBox FrontEnd.View.myBackgroundColorBox private
Definition at line 103 of file View.java.
Referenced by FrontEnd.View.getMyBackgroundColorBox().
List<SuperCommand> FrontEnd.View.myButtons private
Definition at line 95 of file View.java.
CommandFactory FrontEnd.View.myCommandFactory private
Definition at line 93 of file View.java.
CommandLine FrontEnd.View.myCommandLine private
Definition at line 86 of file View.java.
Console FrontEnd.View.myConsole private
Definition at line 89 of file View.java.
Controller FrontEnd.View.myController private
Definition at line 46 of file View.java.
SuperCommand FrontEnd.View.myEnterCommand private
Definition at line 94 of file View.java.
GridCheckBox FrontEnd.View.myGridCheckBox private
Definition at line 105 of file View.java.
Referenced by FrontEnd.View.getMyGridCheckBox().
HistoryBox FrontEnd.View.myHistoryBox private
Definition at line 88 of file View.java.
Referenced by FrontEnd.View.makeTextAreas().
LanguageSelector FrontEnd.View.myLanguageSelector private
Definition at line 99 of file View.java.
Referenced by FrontEnd.View.getLanguageSelector().
PenOptions FrontEnd.View.myPenBox private
Definition at line 102 of file View.java.
Scene FrontEnd.View.myScene private
Definition at line 44 of file View.java.
Referenced by FrontEnd.View.getScene().
TurtleImageBox FrontEnd.View.myTurtleImageBox private
Definition at line 104 of file View.java.
Referenced by FrontEnd.View.getMyTurtleImageBox().
TurtleInformation FrontEnd.View.myTurtleInformation private
Definition at line 100 of file View.java.
Referenced by FrontEnd.View.getTurtleInfo().
TurtleWindow FrontEnd.View.myTurtleWindow private
Definition at line 90 of file View.java.
Referenced by FrontEnd.View.getTurtleWindow().
final int FrontEnd.View.NEWWORKSPACE_BUTTON_WIDTH = 100 static
Definition at line 50 of file View.java.
final Insets FrontEnd.View.PADDING = new Insets(5) static
Definition at line 65 of file View.java.
final int FrontEnd.View.PUFFY_BUTTON_HEIGHT = 60 static
Definition at line 48 of file View.java.
Referenced by FrontEndCommands.EnterCommand.EnterCommand().
BorderPane FrontEnd.View.root package
Definition at line 45 of file View.java.
final int FrontEnd.View.SHORT_BUTTON_HEIGHT = 30 static
Definition at line 47 of file View.java.
Referenced by FrontEndCommands.AmountCommand.AmountCommand(), FrontEndCommands.SetXYCommand.SetXYCommand(), FrontEndCommands.SuperCommand.SuperCommand(), and FrontEndCommands.TowardCommand.TowardCommand().
final int FrontEnd.View.SIDEBAR_AMOUNT_BUTTON_WIDTH = 125 static
Definition at line 59 of file View.java.
Referenced by FrontEndCommands.SuperCommand.SuperCommand().
final int FrontEnd.View.SIDEBAR_AMOUNT_WIDTH = 75 static
Definition at line 60 of file View.java.
Referenced by FrontEndCommands.AmountCommand.AmountCommand(), FrontEndCommands.SetXYCommand.SetXYCommand(), and FrontEndCommands.TowardCommand.TowardCommand().
final int FrontEnd.View.SIDEBAR_BUTTON_WIDTH = 200 static
Definition at line 58 of file View.java.
Referenced by FrontEndCommands.LoadWorkspace.LoadWorkspace(), FrontEndCommands.NewWorkspace.NewWorkspace(), and FrontEndCommands.SaveWorkspace.SaveWorkspace().
final int FrontEnd.View.SIDEBAR_COMBOBOX_WIDTH = 200 static
Definition at line 61 of file View.java.
Referenced by TurtleView.BackgroundColorBox.BackgroundColorBox(), Pen.PenColorBox.PenColorBox(), Pen.PenThicknessBox.PenThicknessBox(), TurtleView.TurtleImageBox.TurtleImageBox(), FrontEnd.UserCommands.UserCommands(), and FrontEnd.UserVariablesStorage.UserVariablesStorage().
final int FrontEnd.View.SIDEBAR_WIDTH = 250 static
Definition at line 57 of file View.java.
VBox FrontEnd.View.sidebarVBox = new VBox(BOX_SPACING) private
Definition at line 77 of file View.java.
HBox FrontEnd.View.topHBox = new HBox(BOX_SPACING) private
Definition at line 74 of file View.java.
final double FrontEnd.View.TURTLEWINDOW_HEIGHT = 400.0 static
Definition at line 68 of file View.java.
Referenced by Backend.Turtle.addLocation(), TurtleView.PointConverter.convertActualToUserY(), TurtleView.PointConverter.convertUserToActualY(), TurtleView.TurtleWindow.makeGrid(), TurtleView.TurtleWindow.makeTurtle(), and TurtleView.TurtleWindow.TurtleWindow().
final double FrontEnd.View.TURTLEWINDOW_WIDTH = 600.0 static
Definition at line 67 of file View.java.
Referenced by Backend.Turtle.addLocation(), TurtleView.PointConverter.convertActualToUserX(), TurtleView.PointConverter.convertUserToActualX(), TurtleView.TurtleWindow.makeGrid(), TurtleView.TurtleWindow.makeTurtle(), and TurtleView.TurtleWindow.TurtleWindow().
HBox FrontEnd.View.usercmdHBox = new HBox(BOX_SPACING) private
Definition at line 78 of file View.java.
HBox FrontEnd.View.uservrbHBox = new HBox(BOX_SPACING) private
Definition at line 79 of file View.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEnd/View.java