slogo_team11: FrontEndCommands.SaveWorkspace Class Reference
FrontEndCommands.SaveWorkspace Class Reference
Public Member Functions
SaveWorkspace (View myView)
Button getButton ()
Static Public Attributes
static final String DIALOG_MESSAGE = "Choose location to save workspace preferences"
static final String ERROR_MESSAGE = "This file was not found"
static final String SAVE_PREFIX = "Save as file: "
static final String PROPERTIES_SUFFIX = ".properties"
static final String DEFAULT_IMAGEPATH = "src\\TurtleView\\images"
Private Member Functions
void handle ()
void chooseFile ()
void writeSettingsToFile ()
Private Attributes
Button myButton
List< File > myImages = new ArrayList<File>()
View myView
File workspaceSettings
Detailed Description
Allows users to set, save, and load workspace preferences (like default background, starting image list, starting number of turtles, starting file to load, command language, etc.)
Author
Rica
Definition at line 20 of file SaveWorkspace.java.
Constructor & Destructor Documentation
FrontEndCommands.SaveWorkspace.SaveWorkspace (View myView)
Definition at line 32 of file SaveWorkspace.java.
References FrontEndCommands.SaveWorkspace.handle(), FrontEndCommands.SaveWorkspace.myView, FrontEnd.DefaultStrings.SAVE_WORKSPACE, and FrontEnd.View.SIDEBAR_BUTTON_WIDTH.
Member Function Documentation
void FrontEndCommands.SaveWorkspace.chooseFile () private
Definition at line 52 of file SaveWorkspace.java.
References FrontEndCommands.SaveWorkspace.PROPERTIES_SUFFIX.
Referenced by FrontEndCommands.SaveWorkspace.handle().
Button FrontEndCommands.SaveWorkspace.getButton ()
Definition at line 79 of file SaveWorkspace.java.
References FrontEndCommands.SaveWorkspace.myButton.
Referenced by FrontEnd.View.View().
void FrontEndCommands.SaveWorkspace.handle () private
Definition at line 39 of file SaveWorkspace.java.
References FrontEndCommands.SaveWorkspace.chooseFile(), and FrontEndCommands.SaveWorkspace.writeSettingsToFile().
Referenced by FrontEndCommands.SaveWorkspace.SaveWorkspace().
void FrontEndCommands.SaveWorkspace.writeSettingsToFile () private
Definition at line 63 of file SaveWorkspace.java.
References TurtleView.TurtleWindow.getAllTurtles(), FrontEnd.LanguageSelector.getCurrentLanguage(), FrontEnd.View.getLanguageSelector(), FrontEnd.View.getMyBackgroundColorBox(), and FrontEnd.View.getTurtleWindow().
Referenced by FrontEndCommands.SaveWorkspace.handle().
Member Data Documentation
final String FrontEndCommands.SaveWorkspace.DEFAULT_IMAGEPATH = "src\\TurtleView\\images" static
Definition at line 30 of file SaveWorkspace.java.
final String FrontEndCommands.SaveWorkspace.DIALOG_MESSAGE = "Choose location to save workspace preferences" static
Definition at line 26 of file SaveWorkspace.java.
final String FrontEndCommands.SaveWorkspace.ERROR_MESSAGE = "This file was not found" static
Definition at line 27 of file SaveWorkspace.java.
Button FrontEndCommands.SaveWorkspace.myButton private
Definition at line 21 of file SaveWorkspace.java.
Referenced by FrontEndCommands.SaveWorkspace.getButton().
List<File> FrontEndCommands.SaveWorkspace.myImages = new ArrayList<File>() private
Definition at line 22 of file SaveWorkspace.java.
View FrontEndCommands.SaveWorkspace.myView private
Definition at line 23 of file SaveWorkspace.java.
Referenced by FrontEndCommands.SaveWorkspace.SaveWorkspace().
final String FrontEndCommands.SaveWorkspace.PROPERTIES_SUFFIX = ".properties" static
Definition at line 29 of file SaveWorkspace.java.
Referenced by FrontEndCommands.SaveWorkspace.chooseFile().
final String FrontEndCommands.SaveWorkspace.SAVE_PREFIX = "Save as file: " static
Definition at line 28 of file SaveWorkspace.java.
File FrontEndCommands.SaveWorkspace.workspaceSettings private
Definition at line 24 of file SaveWorkspace.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEndCommands/SaveWorkspace.java