slogo_team11: TurtleView.TurtleWindow Class Reference
TurtleView.TurtleWindow Class Reference
Public Member Functions
TurtleWindow (PenOptions penBox, TurtleImageBox imageBox, TurtleInformation turtleInfo)
Turtle makeTurtle ()
void update (List< Turtle > updates)
void changeBackgroundColor (String color)
List< Turtle > getActiveTurtles ()
List< Turtle > getAllTurtles ()
void gridLines (boolean gridOn)
Static Public Attributes
static final double ORIGIN_X = 200.0
static final double ORIGIN_Y = 100.0
static final double DEFAULT_ANGLE = 0
static final Color DEFAULT_PEN = Color.BLACK
static final String DEFAULT_BACKGROUND = DefaultStrings.BACKGROUND_COLOR_DEFAULTS.get(0)
static final String DEFAULT_IMAGE = "turtle1"
static final int DEFAULT_TURTLE_INDEX = 0
static final double GRID_INTERVAL = 40.0
static final double GRID_STROKE = 1.0
static final int START_TURTLES = 2
Private Member Functions
void click (Turtle t)
void makeGrid ()
Private Attributes
List< Turtle > allTurtles
List< Turtle > activeTurtles
List< Line > myGridLines
PenOptions myPenBox
TurtleImageBox myTurtleImageBox
TurtleInformation myTurtleInformation
int numTurtles
Detailed Description
Stores the turtle and moves it around when commands are executed.
Author
Greg Lyons, Rica Zhang
Definition at line 22 of file TurtleWindow.java.
Constructor & Destructor Documentation
TurtleView.TurtleWindow.TurtleWindow (PenOptions penBox, TurtleImageBox imageBox, TurtleInformation turtleInfo)
Definition at line 44 of file TurtleWindow.java.
References TurtleView.TurtleWindow.changeBackgroundColor(), TurtleView.TurtleWindow.click(), TurtleView.TurtleWindow.makeGrid(), TurtleView.TurtleWindow.makeTurtle(), TurtleView.TurtleWindow.START_TURTLES, FrontEnd.View.TURTLEWINDOW_HEIGHT, and FrontEnd.View.TURTLEWINDOW_WIDTH.
Member Function Documentation
void TurtleView.TurtleWindow.changeBackgroundColor (String color)
Definition at line 105 of file TurtleWindow.java.
Referenced by TurtleView.BackgroundColorBox.handle(), and TurtleView.TurtleWindow.TurtleWindow().
void TurtleView.TurtleWindow.click (Turtle t) private
Definition at line 71 of file TurtleWindow.java.
References Pen.PenOptions.changePen(), TurtleView.TurtleInformation.changeTurtle(), TurtleView.TurtleImageBox.changeTurtle(), Backend.Turtle.getPen(), Backend.Turtle.hideRing(), and Backend.Turtle.showRing().
Referenced by TurtleView.TurtleWindow.makeTurtle(), and TurtleView.TurtleWindow.TurtleWindow().
List<Turtle> TurtleView.TurtleWindow.getActiveTurtles ()
Definition at line 109 of file TurtleWindow.java.
References TurtleView.TurtleWindow.activeTurtles.
Referenced by FrontEnd.Controller.interpret(), and FrontEnd.Controller.update().
List<Turtle> TurtleView.TurtleWindow.getAllTurtles ()
Definition at line 114 of file TurtleWindow.java.
References TurtleView.TurtleWindow.allTurtles.
Referenced by FrontEndCommands.SaveWorkspace.writeSettingsToFile().
void TurtleView.TurtleWindow.gridLines (boolean gridOn)
Definition at line 159 of file TurtleWindow.java.
Referenced by TurtleView.GridCheckBox.handle().
void TurtleView.TurtleWindow.makeGrid () private
Definition at line 145 of file TurtleWindow.java.
References TurtleView.TurtleWindow.GRID_INTERVAL, FrontEnd.View.TURTLEWINDOW_HEIGHT, and FrontEnd.View.TURTLEWINDOW_WIDTH.
Referenced by TurtleView.TurtleWindow.TurtleWindow().
Turtle TurtleView.TurtleWindow.makeTurtle ()
Definition at line 61 of file TurtleWindow.java.
References TurtleView.TurtleWindow.click(), FrontEnd.View.TURTLEWINDOW_HEIGHT, and FrontEnd.View.TURTLEWINDOW_WIDTH.
Referenced by FrontEnd.View.makeTurtleButton(), and TurtleView.TurtleWindow.TurtleWindow().
void TurtleView.TurtleWindow.update (List< Turtle > updates)
Definition at line 90 of file TurtleWindow.java.
Referenced by FrontEnd.Controller.interpret().
Member Data Documentation
List<Turtle> TurtleView.TurtleWindow.activeTurtles private
Definition at line 37 of file TurtleWindow.java.
Referenced by TurtleView.TurtleWindow.getActiveTurtles().
List<Turtle> TurtleView.TurtleWindow.allTurtles private
Definition at line 36 of file TurtleWindow.java.
Referenced by TurtleView.TurtleWindow.getAllTurtles().
final double TurtleView.TurtleWindow.DEFAULT_ANGLE = 0 static
Definition at line 26 of file TurtleWindow.java.
final String TurtleView.TurtleWindow.DEFAULT_BACKGROUND = DefaultStrings.BACKGROUND_COLOR_DEFAULTS.get(0) static
Definition at line 28 of file TurtleWindow.java.
final String TurtleView.TurtleWindow.DEFAULT_IMAGE = "turtle1" static
Definition at line 29 of file TurtleWindow.java.
final Color TurtleView.TurtleWindow.DEFAULT_PEN = Color.BLACK static
Definition at line 27 of file TurtleWindow.java.
final int TurtleView.TurtleWindow.DEFAULT_TURTLE_INDEX = 0 static
Definition at line 30 of file TurtleWindow.java.
final double TurtleView.TurtleWindow.GRID_INTERVAL = 40.0 static
Definition at line 32 of file TurtleWindow.java.
Referenced by TurtleView.TurtleWindow.makeGrid().
final double TurtleView.TurtleWindow.GRID_STROKE = 1.0 static
Definition at line 33 of file TurtleWindow.java.
List<Line> TurtleView.TurtleWindow.myGridLines private
Definition at line 38 of file TurtleWindow.java.
PenOptions TurtleView.TurtleWindow.myPenBox private
Definition at line 39 of file TurtleWindow.java.
TurtleImageBox TurtleView.TurtleWindow.myTurtleImageBox private
Definition at line 40 of file TurtleWindow.java.
TurtleInformation TurtleView.TurtleWindow.myTurtleInformation private
Definition at line 41 of file TurtleWindow.java.
int TurtleView.TurtleWindow.numTurtles private
Definition at line 42 of file TurtleWindow.java.
final double TurtleView.TurtleWindow.ORIGIN_X = 200.0 static
Definition at line 24 of file TurtleWindow.java.
final double TurtleView.TurtleWindow.ORIGIN_Y = 100.0 static
Definition at line 25 of file TurtleWindow.java.
final int TurtleView.TurtleWindow.START_TURTLES = 2 static
Definition at line 34 of file TurtleWindow.java.
Referenced by TurtleView.TurtleWindow.TurtleWindow().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/TurtleView/TurtleWindow.java