slogo_team11: FrontEnd.StringChooser Class Reference
FrontEnd.StringChooser Class Reference
Static Public Member Functions
static String getWordInLang (String language, String wordToAdd)
Static Public Attributes
static List< String > myLanguageOrder
Static Private Attributes
static final ResourceBundle myLanguages = ResourceBundle.getBundle(DefaultStrings.DEFAULT_RESOURCE_PACKAGE)
Detailed Description
String selector so that text can be selected in the correct language
Author
Rica
Definition at line 12 of file StringChooser.java.
Member Function Documentation
static String FrontEnd.StringChooser.getWordInLang (String language, String wordToAdd) static
Definition at line 18 of file StringChooser.java.
Referenced by FrontEnd.View.makeClearButton(), FrontEnd.View.makeTextAreas(), FrontEnd.View.makeTurtleButton(), FrontEndCommands.NewWorkspace.NewWorkspace(), FrontEndCommands.SuperCommand.SuperCommand(), FrontEnd.UserCommands.UserCommands(), FrontEnd.UserVariablesStorage.UserVariablesStorage(), and FrontEnd.View.View().
Member Data Documentation
List<String> FrontEnd.StringChooser.myLanguageOrder static
Initial value:
= Arrays.asList(new String[]{DefaultStrings.ENGLISH, DefaultStrings.CHINESE,
                                                                             DefaultStrings.FRENCH, DefaultStrings.ITALIAN,
                                                                             DefaultStrings.PORTUGUESE, DefaultStrings.RUSSIAN})
Definition at line 13 of file StringChooser.java.
Referenced by FrontEnd.LanguageSelector.handle(), and FrontEnd.LanguageSelector.LanguageSelector().
final ResourceBundle FrontEnd.StringChooser.myLanguages = ResourceBundle.getBundle(DefaultStrings.DEFAULT_RESOURCE_PACKAGE) static private
Definition at line 16 of file StringChooser.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/FrontEnd/StringChooser.java