slogo_team11: Backend.SceneUpdater Class Reference
Backend.SceneUpdater Class Reference
Public Member Functions
SceneUpdater (List< Turtle > activeTurtles, List< Double > printValues, boolean nE)
List< String > getVariables ()
List< UserVariable > constructAllVariables ()
List< Turtle > getTurtles ()
List< Double > getReturnValues ()
boolean isNoError ()
String getErrorMessage ()
Private Attributes
List< String > myVariables
boolean noError
String errorMessage
List< Turtle > turtles
List< Double > returnValues
Detailed Description
This class is an interface between the front-end and the back-end. For each command that is parsed, the back-end creates a new SceneUpdater. Each SceneUpdater instance tells the View how to update the display (is the pen up/down, was there an error message, where does the turtle move, etc.)
Author
Greg, Rica, Ashwin, Justin
Definition at line 17 of file SceneUpdater.java.
Constructor & Destructor Documentation
Backend.SceneUpdater.SceneUpdater (List< Turtle > activeTurtles, List< Double > printValues, boolean nE)
Definition at line 25 of file SceneUpdater.java.
References FrontEnd.DefaultStrings.ERROR_DEFAULT.
Member Function Documentation
List<UserVariable> Backend.SceneUpdater.constructAllVariables ()
Creates a UserVariable object for each variable that the user created in their command.
Returns
List of UserVariables created
Definition at line 41 of file SceneUpdater.java.
String Backend.SceneUpdater.getErrorMessage ()
Definition at line 62 of file SceneUpdater.java.
References Backend.SceneUpdater.errorMessage.
Referenced by FrontEnd.Controller.interpret().
List<Double> Backend.SceneUpdater.getReturnValues ()
Definition at line 54 of file SceneUpdater.java.
References Backend.SceneUpdater.returnValues.
Referenced by FrontEnd.Controller.interpret().
List<Turtle> Backend.SceneUpdater.getTurtles ()
Definition at line 50 of file SceneUpdater.java.
References Backend.SceneUpdater.turtles.
Referenced by FrontEnd.Controller.interpret().
List<String> Backend.SceneUpdater.getVariables ()
Definition at line 33 of file SceneUpdater.java.
References Backend.SceneUpdater.myVariables.
Referenced by FrontEnd.Controller.interpret().
boolean Backend.SceneUpdater.isNoError ()
Definition at line 58 of file SceneUpdater.java.
References Backend.SceneUpdater.noError.
Referenced by FrontEnd.Controller.interpret().
Member Data Documentation
String Backend.SceneUpdater.errorMessage private
Definition at line 20 of file SceneUpdater.java.
Referenced by Backend.SceneUpdater.getErrorMessage().
List<String> Backend.SceneUpdater.myVariables private
Definition at line 18 of file SceneUpdater.java.
Referenced by Backend.SceneUpdater.getVariables().
boolean Backend.SceneUpdater.noError private
Definition at line 19 of file SceneUpdater.java.
Referenced by Backend.SceneUpdater.isNoError().
List<Double> Backend.SceneUpdater.returnValues private
Definition at line 22 of file SceneUpdater.java.
Referenced by Backend.SceneUpdater.getReturnValues().
List<Turtle> Backend.SceneUpdater.turtles private
Definition at line 21 of file SceneUpdater.java.
Referenced by Backend.SceneUpdater.getTurtles().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Backend/SceneUpdater.java