slogo_team11: Pen.Pen Class Reference
Pen.Pen Class Reference
Public Member Functions
Pen ()
Polyline drawLines (List< Point2D > pointList)
void setPenDown ()
void setPenUp ()
void changeColor (Color c)
void changeThick (double thick)
void changeType (List< Double > type)
boolean isDown ()
Static Public Attributes
static final double DEFAULT_THICKNESS = 1.0
static final Color DEFAULT_COLOR = Color.BLACK
static final List< Double > SOLID = new ArrayList<Double>()
static final List< Double > DASHED = new ArrayList<Double>(Arrays.asList(10.0,10.0))
static final List< Double > DOTTED = new ArrayList<Double>(Arrays.asList(2.0, 35.0))
Private Member Functions
double[] pointListToArray (List< Point2D > myList)
Private Attributes
boolean penDown
List< Double > myLineType
Color myColor
double myThickness
Detailed Description
Definition at line 10 of file Pen.java.
Constructor & Destructor Documentation
Pen.Pen.Pen ()
Definition at line 23 of file Pen.java.
Member Function Documentation
void Pen.Pen.changeColor (Color c)
Definition at line 60 of file Pen.java.
void Pen.Pen.changeThick (double thick)
Definition at line 65 of file Pen.java.
void Pen.Pen.changeType (List< Double > type)
Definition at line 69 of file Pen.java.
Polyline Pen.Pen.drawLines (List< Point2D > pointList)
Definition at line 30 of file Pen.java.
Referenced by Backend.Turtle.moveAndDrawPath().
boolean Pen.Pen.isDown ()
Definition at line 73 of file Pen.java.
Referenced by Backend.Turtle.penStatus().
double [] Pen.Pen.pointListToArray (List< Point2D > myList) private
Definition at line 43 of file Pen.java.
void Pen.Pen.setPenDown ()
Definition at line 52 of file Pen.java.
Referenced by Backend.Turtle.setPenDown().
void Pen.Pen.setPenUp ()
Definition at line 56 of file Pen.java.
Referenced by Backend.Turtle.setPenUp().
Member Data Documentation
final List<Double> Pen.Pen.DASHED = new ArrayList<Double>(Arrays.asList(10.0,10.0)) static
Definition at line 20 of file Pen.java.
final Color Pen.Pen.DEFAULT_COLOR = Color.BLACK static
Definition at line 18 of file Pen.java.
final double Pen.Pen.DEFAULT_THICKNESS = 1.0 static
Definition at line 17 of file Pen.java.
final List<Double> Pen.Pen.DOTTED = new ArrayList<Double>(Arrays.asList(2.0, 35.0)) static
Definition at line 21 of file Pen.java.
Color Pen.Pen.myColor private
Definition at line 14 of file Pen.java.
List<Double> Pen.Pen.myLineType private
Definition at line 13 of file Pen.java.
double Pen.Pen.myThickness private
Definition at line 15 of file Pen.java.
boolean Pen.Pen.penDown private
Definition at line 12 of file Pen.java.
final List<Double> Pen.Pen.SOLID = new ArrayList<Double>() static
Definition at line 19 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Pen/Pen.java