slogo_team11: Pen.PenOptions Class Reference
Pen.PenOptions Class Reference
Public Member Functions
PenOptions (Pen p)
void changePen (Pen p)
Private Member Functions
void setUpBoxes ()
void updatePen ()
Private Attributes
Pen myPen
PenColorBox myColorBox
CheckBox myDownBox
PenThicknessBox myThickBox
PenTypeBox myTypeBox
Detailed Description
Definition at line 10 of file PenOptions.java.
Constructor & Destructor Documentation
Pen.PenOptions.PenOptions (Pen p)
Definition at line 19 of file PenOptions.java.
References FrontEnd.View.BOX_SPACING, and Pen.PenOptions.setUpBoxes().
Member Function Documentation
void Pen.PenOptions.changePen (Pen p)
Definition at line 54 of file PenOptions.java.
Referenced by TurtleView.TurtleWindow.click().
void Pen.PenOptions.setUpBoxes () private
Definition at line 25 of file PenOptions.java.
References FrontEnd.View.BOX_SPACING, FrontEnd.DefaultStrings.COLOR_LABEL, Pen.PenColorBox.getColor(), Pen.PenThicknessBox.getThick(), Pen.PenTypeBox.getType(), FrontEnd.DefaultStrings.PENDOWN_LABEL, FrontEnd.DefaultStrings.THICKNESS_LABEL, FrontEnd.DefaultStrings.TYPEBOX_LABEL, and Pen.PenOptions.updatePen().
Referenced by Pen.PenOptions.PenOptions().
void Pen.PenOptions.updatePen () private
Definition at line 49 of file PenOptions.java.
Referenced by Pen.PenOptions.setUpBoxes().
Member Data Documentation
PenColorBox Pen.PenOptions.myColorBox private
Definition at line 14 of file PenOptions.java.
CheckBox Pen.PenOptions.myDownBox private
Definition at line 15 of file PenOptions.java.
Pen Pen.PenOptions.myPen private
Definition at line 12 of file PenOptions.java.
PenThicknessBox Pen.PenOptions.myThickBox private
Definition at line 16 of file PenOptions.java.
PenTypeBox Pen.PenOptions.myTypeBox private
Definition at line 17 of file PenOptions.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Pen/PenOptions.java