slogo_team11: TurtleView.TurtleInformation Class Reference
TurtleView.TurtleInformation Class Reference
Public Member Functions
TurtleInformation (Turtle t)
void changeTurtle (Turtle t)
void update ()
Private Member Functions
void emptyInfo ()
double truncate (double val)
Private Attributes
Turtle myTurtle
Label turtleIndexLabel
Label turtlePositionLabel
Label turtleDirectionLabel
Detailed Description
Tells the user information about the turtle, updates whenever the turtle changes because it is an observer of the turtle
Author
Greg Lyons, Rica Zhang
Definition at line 12 of file TurtleInformation.java.
Constructor & Destructor Documentation
TurtleView.TurtleInformation.TurtleInformation (Turtle t)
Definition at line 19 of file TurtleInformation.java.
References TurtleView.TurtleInformation.changeTurtle().
Member Function Documentation
void TurtleView.TurtleInformation.changeTurtle (Turtle t)
Definition at line 27 of file TurtleInformation.java.
References TurtleView.TurtleInformation.update().
Referenced by TurtleView.TurtleWindow.click(), and TurtleView.TurtleInformation.TurtleInformation().
void TurtleView.TurtleInformation.emptyInfo () private
Definition at line 42 of file TurtleInformation.java.
Referenced by TurtleView.TurtleInformation.update().
double TurtleView.TurtleInformation.truncate (double val) private
Definition at line 48 of file TurtleInformation.java.
Referenced by TurtleView.TurtleInformation.update().
void TurtleView.TurtleInformation.update ()
Definition at line 32 of file TurtleInformation.java.
References TurtleView.TurtleInformation.emptyInfo(), Backend.Turtle.getID(), Backend.Turtle.getXCord(), Backend.Turtle.getYCord(), and TurtleView.TurtleInformation.truncate().
Referenced by TurtleView.TurtleInformation.changeTurtle(), Backend.Turtle.move(), and FrontEnd.View.updateTurtleInfo().
Member Data Documentation
Turtle TurtleView.TurtleInformation.myTurtle private
Definition at line 13 of file TurtleInformation.java.
Label TurtleView.TurtleInformation.turtleDirectionLabel private
Definition at line 17 of file TurtleInformation.java.
Label TurtleView.TurtleInformation.turtleIndexLabel private
Definition at line 15 of file TurtleInformation.java.
Label TurtleView.TurtleInformation.turtlePositionLabel private
Definition at line 16 of file TurtleInformation.java.
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/TurtleView/TurtleInformation.java