slogo_team11: Backend.Parser Class Reference
Backend.Parser Class Reference
Public Member Functions
Parser ()
void newInfo (String input, Turtle turtle, String language)
Queue< Node > getQueueOfNodes ()
String checkSaveType ()
String getVariableName ()
double getVariableValue ()
String[] getFunctionBody ()
String[] getFunctionParams ()
String getFunctionName ()
boolean getNoError ()
Map< String, ConstantNode > getMap ()
Private Member Functions
String[] convert (String[] array)
Map< String, String > convertResourceBundleToMap (ResourceBundle resource)
String getNextString (String str, String[] array)
Private Attributes
String[] splitWords
Turtle myTurtle
Map< String, String > myMap
boolean noError
Map< String, ConstantNode > daMap
Static Private Attributes
static final String[] Packages
Detailed Description
Author
: Justin Carrao, Ashwin Kommajesula This class is the one that parses the string instructions passed to the back end It is designed to help the interpreter class, basically.
Definition at line 23 of file Parser.java.
Constructor & Destructor Documentation
Backend.Parser.Parser ()
Definition at line 33 of file Parser.java.
Member Function Documentation
String Backend.Parser.checkSaveType ()
Definition at line 142 of file Parser.java.
String [] Backend.Parser.convert (String[] array) private
converts will make each of the strings general to take into account the different types of input for the same node use a properties file
Parameters
array
Returns
Definition at line 53 of file Parser.java.
Referenced by Backend.Parser.newInfo().
Map<String, String> Backend.Parser.convertResourceBundleToMap (ResourceBundle resource) private
Definition at line 73 of file Parser.java.
Referenced by Backend.Parser.newInfo().
String [] Backend.Parser.getFunctionBody ()
Definition at line 161 of file Parser.java.
References Backend.Parser.splitWords.
String Backend.Parser.getFunctionName ()
Definition at line 194 of file Parser.java.
String [] Backend.Parser.getFunctionParams ()
Definition at line 175 of file Parser.java.
Map<String, ConstantNode> Backend.Parser.getMap ()
Definition at line 202 of file Parser.java.
References Backend.Parser.daMap.
Referenced by Backend.Model.makeTreeandAddValues().
String Backend.Parser.getNextString (String str, String[] array) private
Definition at line 87 of file Parser.java.
Referenced by Backend.Parser.getQueueOfNodes().
boolean Backend.Parser.getNoError ()
Definition at line 198 of file Parser.java.
References Backend.Parser.noError.
Referenced by Backend.Model.makeTreeandAddValues().
Queue<Node> Backend.Parser.getQueueOfNodes ()
Definition at line 91 of file Parser.java.
References Backend.Parser.getNextString().
Referenced by Backend.Model.makeTreeandAddValues().
String Backend.Parser.getVariableName ()
Definition at line 153 of file Parser.java.
double Backend.Parser.getVariableValue ()
Definition at line 157 of file Parser.java.
void Backend.Parser.newInfo (String input, Turtle turtle, String language)
Definition at line 37 of file Parser.java.
References Backend.Parser.convert(), and Backend.Parser.convertResourceBundleToMap().
Referenced by Backend.Model.makeTreeandAddValues().
Member Data Documentation
Map<String, ConstantNode> Backend.Parser.daMap private
Definition at line 31 of file Parser.java.
Referenced by Backend.Parser.getMap().
Map<String, String> Backend.Parser.myMap private
Definition at line 27 of file Parser.java.
Turtle Backend.Parser.myTurtle private
Definition at line 26 of file Parser.java.
boolean Backend.Parser.noError private
Definition at line 30 of file Parser.java.
Referenced by Backend.Parser.getNoError().
final String [] Backend.Parser.Packages static private
Initial value:
= { "", "booleans.", "loops.",
            "math.", "turtlecommands." }
Definition at line 28 of file Parser.java.
String [] Backend.Parser.splitWords private
Definition at line 25 of file Parser.java.
Referenced by Backend.Parser.getFunctionBody().
The documentation for this class was generated from the following file:
/tmp/duke-compsci308-fall2014/slogo_team11/repository/src/Backend/Parser.java